### ISSUE TITLE
Maintained Order

### ISSUE THREAD

**Issue by pauljmartinez** [c2h5oh/hide#2]
Could you let me know if I'm reading this wrong?

```
So what do we want?
...
maintained order (older ID < newer ID)
...
```

I was expecting to see the Marshaled ids to still be in maintained order.

```
Sample Results
Consecutive IDs
  308035 -> 1178570333
  308036 ->  531536956
  308037 -> 2031987227
  308038 -> 1384953850
```

Thx!

**Comment by c2h5oh** [comment]
I should have worded it better.
What I meant is that since this obfuscation is reversible and "cheap" you don't store obfuscated IDs, just the original ones: marshaling obfuscates, unmarshaling deobfuscates. Because of that you can simply keep using consecutive numbers (such as autoincrement field in db).

By comparison if obfuscation was one way, you used random IDs etc the order would be gone.
